project:
  type: website
  output-dir: docs

website:
  title: "Khoi.T.Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects.qmd
            text: "F1 SQL Analysis"
          - href: Project3.qmd
            text: "Love, Fear, and Social Worlds: A Text Analysis of Pride and Prejudice, Frankenstein, and Dracula"
          - href: project4.qmd
            text: "aRtpalette"
          - href: Paper_presentation_poster.html
            text: "Paper Analysis: DuckDB: An Embeddable Analytical Database"
          - href: TitanicProject.html
            text: "Survival on the Titanic: Analyzing Patterns and Building Predictive Models"
            
      - href: Resume.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/kho2934

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false